# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: sjennett <sjennett@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/11/04 15:21:19 by sjennett          #+#    #+#              #
#    Updated: 2021/03/08 17:51:31 by sjennett         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


SRCS	= get_next_line.c get_next_line_utils.c ft_atoi.c ft_isalnum.c ft_isalpha.c ft_isascii.c  ft_isdigit.c ft_isprint.c ft_strchr.c ft_strlcat.c ft_strlcpy.c ft_strlen.c ft_strncmp.c ft_strnstr.c ft_strrchr.c ft_tolower.c ft_toupper.c ft_memset.c ft_memcmp.c ft_memchr.c ft_memmove.c ft_memcpy.c ft_memccpy.c ft_bzero.c ft_substr.c ft_strjoin.c ft_strtrim.c ft_split.c ft_itoa.c ft_strmapi.c ft_putchar_fd.c ft_putnbr_fd.c ft_putstr_fd.c ft_putendl_fd.c ft_calloc.c ft_strdup.c

BONUS_SRCS = ft_lstnew.c ft_lstadd_front.c ft_lstsize.c ft_lstlast.c ft_lstadd_back.c ft_lstdelone.c ft_lstclear.c ft_lstiter.c ft_lstmap.c

OBJ		= ${SRCS:.c=.o}

BONUS_OBJ = $(BONUS_SRCS:.c=.o)

HEADER	= -I libft.h 

CFLAGS	= -Wall -Wextra -Werror

CC		= gcc
.c.o:	${HEADER}
			${CC} ${CFLAGS} -c $< -o ${<:.c=.o}

rm		= rm -f

NAME	= libft.a

${NAME}:${OBJ}
			ar rc ${NAME} ${OBJ}
			ranlib $(NAME)

bonus: $(OBJ) $(BONUS_OBJ)
			ar rc $(NAME) $(OBJ) $(BONUS_OBJ)

all:	${NAME}

clean:
			${RM} ${OBJ} *.gch
			$(RM) $(BONUS_OBJ)

fclean:	clean
			${RM} ${NAME}

re:		fclean all

.PHONY:	all clean fclean re bonus
